In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.datasets import load_iris



In [8]:
x,y=load_iris(return_X_y=True)

In [9]:
pd.DataFrame(x)

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20)

In [12]:
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)

In [15]:
y_pred

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 0, 2,
       0, 2, 1, 0, 1, 1, 1, 2])

In [13]:
y_test

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 0, 2,
       0, 2, 1, 0, 1, 1, 1, 2])

In [14]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  0, 10]])

In [16]:
ac=accuracy_score(y_test,y_pred)
ac

1.0

In [17]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

